services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/usr/src/app
    ports:
      - "8000:8000"
    env_file:
      - .env.dev
    depends_on:
      db:
        condition: service_healthy
    networks:
      - bookstore_network
  db:
    image: postgres:16.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=dev
      - POSTGRES_PASSWORD=dev
      - POSTGRES_DB=bookstore_db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U dev -d bookstore_db"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - bookstore_network

networks:
  bookstore_network:
    driver: bridge

volumes:
  postgres_data:
